eureka:
  client:
    rest-template-timeout:
      connect-timeout: 5000
      connect-request-timeout: 8000
      socket-timeout: 10000
    fetch-registry: false
    register-with-eureka: false
    healthcheck:
      enabled: true
  server:
    enable-self-preservation: false
    enable-peer-replication: false
    authentication:
      enabled: true
      user:
        name: hechunhui
        password: hechunhui520..
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 30
server:
  port: 20000
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always